CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "Tenants" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Slug" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "StripeCustomerId" character varying(100),
        "StripeSubscriptionId" character varying(100),
        "SubscriptionStatus" character varying(50),
        CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "Projects" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Projects_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "SystemSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "CompanyName" character varying(200),
        "CompanyAddress" character varying(1000),
        "NextInvoiceSequence" integer NOT NULL,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SystemSettings_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "Email" character varying(256) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "PasswordHash" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "Invoices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProjectId" integer NOT NULL,
        "InvoiceNumber" character varying(50) NOT NULL,
        "CompanyName" character varying(200),
        "ClientName" character varying(200),
        "ClientAddress" character varying(1000),
        "DueDate" timestamp with time zone,
        "TaxRate" numeric(5,2) NOT NULL,
        "Notes" text,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Invoices_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "Tasks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProjectId" integer NOT NULL,
        "ParentTaskId" integer,
        "Title" character varying(500) NOT NULL,
        "Description" character varying(4000),
        "Status" text NOT NULL,
        "IsInvoiced" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tasks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tasks_Tasks_ParentTaskId" FOREIGN KEY ("ParentTaskId") REFERENCES "Tasks" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "ExternalLogins" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Provider" character varying(50) NOT NULL,
        "ProviderSubjectId" character varying(256) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExternalLogins" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExternalLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "InvoiceLineItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "InvoiceId" integer NOT NULL,
        "TaskId" integer NOT NULL,
        "Description" character varying(500) NOT NULL,
        "Hours" numeric(10,2) NOT NULL,
        "HourlyRate" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_InvoiceLineItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InvoiceLineItems_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_InvoiceLineItems_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE TABLE "TimeEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TaskId" integer NOT NULL,
        "Hours" numeric(10,2) NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TimeEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TimeEntries_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE UNIQUE INDEX "IX_ExternalLogins_Provider_ProviderSubjectId" ON "ExternalLogins" ("Provider", "ProviderSubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_ExternalLogins_UserId" ON "ExternalLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_InvoiceLineItems_InvoiceId" ON "InvoiceLineItems" ("InvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_InvoiceLineItems_TaskId" ON "InvoiceLineItems" ("TaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_Invoices_ProjectId" ON "Invoices" ("ProjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_Projects_TenantId" ON "Projects" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_SystemSettings_TenantId" ON "SystemSettings" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_Tasks_ParentTaskId" ON "Tasks" ("ParentTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_Tasks_ProjectId" ON "Tasks" ("ProjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE UNIQUE INDEX "IX_Tenants_Slug" ON "Tenants" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_TimeEntries_TaskId" ON "TimeEntries" ("TaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    CREATE INDEX "IX_Users_TenantId" ON "Users" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515171432_AddStripeToTenant') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515171432_AddStripeToTenant', '10.0.0-preview.3.25171.6');
    END IF;
END $EF$;
COMMIT;

